# Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include:
  - .common-ci.yml

stages:
  - image
  - lint
  - build
  - test
  - release

.build-image:
  variables:
    BUILDIMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-build

build-dev-image:
  stage: image
  extends:
    - .build-image
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - apk --no-cache add make bash
    - make .build-image
    - make .push-build-image

.pull-build-image:
  extends:
    - .build-image
  variables:
    SKIP_IMAGE_BUILD: "yes"
  before_script:
    - apk --no-cache add make bash
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - make BUILDIMAGE="${BUILDIMAGE}" .pull-build-image

.lint:
  extends:
    - .pull-build-image
  stage: lint
  allow_failure: true

fmt:
  extends:
    - .lint
  script:
    - make docker-assert-fmt

vet:
  extends:
    - .lint
  script:
    - make docker-vet

lint:
  extends:
    - .lint
  script:
    - make docker-lint

build:
  extends:
    - .pull-build-image
  stage: build
  script:
    - make docker-build

unit-tests:
  extends:
    - .pull-build-image
  stage: test
  script:
    - make docker-test

build-and-push-mig-manager-ubi8:
  extends:
    - .build-and-push-mig-manager
    - .dist-ubi8

build-and-push-mig-manager-ubuntu20:
  extends:
    - .build-and-push-mig-manager
    - .dist-ubuntu20
