version: "2"
linters:
  enable:
    - contextcheck
    - gocritic
    - gosec
    - misspell
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: pkg/mig/config/config_test.go
        text: G404
      - path: (.+)\.go$
        text: 'G115: integer overflow conversion(.+)'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NVIDIA/mig-parted
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
