version: v1
mig-configs:
  all-disabled:
    - devices: all
      mig-enabled: false

  all-1g.10gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.10gb": 8

  all-2g.20gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "2g.20gb": 4

  all-4g.40gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "4g.40gb": 2

  all-8g.80gb:
    - devices: all
      mig-enabled: true
      mig-devices:
        "8g.80gb": 1

  all-balanced:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.10gb": 2
        "2g.20gb": 1
        "4g.40gb": 1
